### PR TITLE
Update Main.php

### PR DESCRIPTION
**Pull request by mikeygio10**

### CODE REVIEW

**Comment by justin-eckenweber** [comment]
I will make the messages configurable in the next version. don't worry!
But thanks for the suggestion :) I will change this

**Comment by mikeygio10** [comment]
ok i am sorry about that

**Comment by mikeygio10** [comment]
its a very nice plugin tho

**Comment by justin-eckenweber** [comment]
Thank you! No problem

**Comment by justin-eckenweber** [comment]
If you really like it, it would be nice if you leave a rating at poggit. it helps very much

**Pull request closed without merging**
